# Generated by Django 6.0.6 on 2026-06-20 16:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_users_options_alter_users_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cin',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(regex='^[A-Z]{1,2}[0-9]{6,7}$')], verbose_name='CIN'),
        ),
    ]
