# Generated by Django 6.0.6 on 2026-06-20 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان التنبيه')),
                ('description', models.TextField(blank=True, null=True, verbose_name='نص التنبيه التفصيلي')),
                ('notification_type', models.CharField(choices=[('booking_new', 'حجز جديد قادم'), ('booking_update', 'تحديث على حالة الحجز'), ('message_new', 'رسالة جديدة'), ('system_alert', 'تنبيه من الإدارة')], default='system_alert', max_length=20, verbose_name='نوع التنبيه')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت القراءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التنبيه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
            ],
            options={
                'verbose_name': 'تنبيه',
                'verbose_name_plural': 'التنبيهات',
                'ordering': ['-created_at'],
            },
        ),
    ]
