# Generated by Django 6.0.7 on 2026-08-01 19:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0002_alter_categorys_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorys',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
