# Generated by Django 6.0.6 on 2026-07-04 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='Category.categorys'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
