# Generated by Django 6.0.7 on 2026-08-01 19:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_alter_service_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
