# Generated by Django 6.0.6 on 2026-06-20 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('payment_method', models.CharField(choices=[('paypal', 'باي بال'), ('card', 'بطاقة بنكية'), ('cash', 'نقداً / عند الحضور')], default='card', max_length=20, verbose_name='وسيلة الدفع')),
                ('status', models.CharField(choices=[('pending', 'في انتظار الدفع'), ('successful', 'ناجح'), ('failed', 'فاشل'), ('refunded', 'مسترجع')], default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='رقم المعاملة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='Bookings.booking', verbose_name='الحجز المرتبط')),
            ],
            options={
                'verbose_name': 'عملية دفع',
                'verbose_name_plural': 'عمليات الدفع',
                'ordering': ['-created_at'],
            },
        ),
    ]
